name: Actions Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      nginx:
        image: nginx
        ports:
          - 8090:80
        volumes:
          - ${{github.workspace}}/nginx/conf.d:/etc/nginx/conf.d
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '9.0.0'

      - name: Install Zip
        uses: montudor/action-zip@v1
        
      - name: Request
        run: |
          curl -vv http://localhost:8090
