name: Actions Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      nginx:
        image: nginx
        ports:
          - 8090:80
        volumes:
          - ${{github.workspace}}/nginx/conf.d:/etc/nginx/conf.d
          
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v2
        
      - name: Request
        run: |
          curl -vv http://localhost:8090
