name: Matrix Actions Test

on:
  push:
    branches: [master]
    
env:
  SERVICENODE: 4

jobs:
 frontend-deploy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Extract and log the JSON key-values.
      run: |
        keys_and_values=$(echo ${{ secrets.SERVICENODE }} | jq -r 'to_entries[] | "\(.key)=\(.value)"')
        for key_value in $keys_and_values; do
          echo $key_value >> $GITHUB_ENV
        done
        
    - name: Extract value only
      run: |
        echo "Fisrtname is ${{ env.fname }}
        echo "Lastname is ${{ env.lname }}"
        
          
    
