name: Matrix Actions Test

on:
  push:
    branches: [master]
    
env:
  SERVICENODE: 4

jobs:
 frontend-deploy:
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::${{secrets.LIVE_SERVER}}"

    - name: get-matrix
      run: |
        COUNTER=1; while [  $COUNTER -le ${{ env.SERVICENODES }} ]; do
          echo "SERVICE${COUNTER}=${{fromJSON(steps.set-matrix.outputs.matrix).SERVICE${COUNTER}}}"  >> $GITHUB_ENV
          COUNTER=$(( $COUNTER +1 ))
        done
        
    - name: Get variables
      run: |
        echo "SERVICE1 = ${{env.SERVICE1}}"
        echo "SERVICE2 = ${{env.SERVICE2}}"
